[package]
name = "tera-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.9.11"
tera = "1.17.0"
yaml-rust = "0.4.5"
